ifndef::imagesdir[:imagesdir: ../images]

[[section-architecture-constraints]]
== Architecture Constraints

[options="header",cols="1,2"]
|===
|Architecture Constraint |Reason
|Web app | The app we are developing is a web game called WIQ consisting of questions and answers generated automatically and users, logged in, must answer to win prizes. 
|Documentation | PlantUML and ASCIIDoc will be used along with the Arc42 template to keep the documentation updated throughout the development of the web app.
|API | To generate the questions and answers for the game we will use tha API of wikidata as it is a great source of information to be able to provide
different types of questions to the users and make the game versatil and not repetitive.
|Question generator | 
|===

[role="arc42help"]
****
.Contents
Any requirement that constraints software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)


.Further Information

See https://docs.arc42.org/section-2/[Architecture Constraints] in the arc42 documentation.

****
