ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy

Summary and explanation of the fundamental decisions and solution strategies that we are going to follow while we develop the web app WIQ.

=== Technology decisions
* Javascript as the programming language. It was chosen as the best option among the others we considered (Java, Spring Boot, etc) as it is well-suited for using APIs easily and is a simple language.
* React.js as the Javascript library chosen to program the user interface of the app due to its ease of use and popularity nowadays.
* Wikidata API to use in the question generator, as it is a requirement of the app.
* Docker for deploying de app locally and testing it.

=== Top-level decomposition of the system decisions
The system will be separated into different microservices, one for each characteristic of the app. It consists of modules or packages with classes dedicated to only one responsibility each. 
We decided to do it this way so that each developer can program their own feature in their branch, reducing potential conflicts when merging code.

=== How to achieve key quality goals decisions
We want the web app to be quick and easy to use, as well as to keep all the users' data secure in the system. To make this possible, 
Docker will help by providing a way to test every aspect of the app before making the release. Moreover, 
multiple tests will be done to ensure everything works as intended.

=== Relevant organizational decisions
* Github will be used to keep all of our code modifications saved and to have Git version control.
    - Issues will be used to assign tasks to the members.
    - Projects will be used to track the progress of the tasks.
* A Whatsapp group will be used to communicate instantly with each other about important matters.

[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.


.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

****
