ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy

Summary and explanation of the fundamental decisions and solution strategies that we are going to follow while we develop the web app WIQ.

=== Technology decisions
* Javascript as the language to program in. The best option between the ones we considered as it is the best suited to use APIs easily in our opinion.
* React.js as the Javascript library chosen to program the user interface of the app as it is easy to use and really famous nowadays.
* Wikidata API to use in the question generator as it is a requirement of the app.
* Docker to deploy de app locally and test it.

=== Top-level decomposition of the system decisions

=== How to achieve key quality goals decisions

=== Relevant organizational decisions
* Github to keep all of our modifications of the code saved and to have Git version control.

[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.


.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

****
