ifndef::imagesdir[:imagesdir: ../images]

[[section-design-decisions]]
== Architecture Decisions

|===
|Decision |Reason
|React.js |We decided to use React.js because it is one of the most popular libraries of Javascript most used nowadays
and we thought that, even though not even one of us knew how to use it, it would make programming the front-end part of the app better
and easier for us.
|Javascript |Our decision was to stick with Javascript for the development of this web app because we already knew about this languaje
from other subjects and we thought it was an easy languaje to be able to do everything that the app requires in matters of using APIs like the one from wikidata
and other things.
|===

[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationales.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. 
Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* ADR (https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions[Documenting Architecture Decisions]) for every important decision
* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision

.Further Information

See https://docs.arc42.org/section-9/[Architecture Decisions] in the arc42 documentation.
There you will find links and examples about ADR.

****
