openapi: 3.0.0
info:
  title: Gatewayservice API
  description: Gateway OpenAPI specification.
  version: 0.2.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: http://SOMEIP:8000
    description: Production server
paths:
  /adduser:
    post:
      summary: Add a new user to the database.
      operationId: addUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: User ID.
                password:
                  type: string
                  description: User password.
      responses:
        '200':
          description: User added successfully.
        '400':
          description: Failed to add user. Posible errors "Password must be at least 8 characters long" and "Password must contain at least one lowercase letter, one uppercase letter, one digit, and one symbol"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error information.
  /health:
    get:
      summary: Check the health status of the service.
      operationId: checkHealth
      responses:
        '200':
          description: Service is healthy.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Health status.
  /login:
    post:
      summary: Log in to the system.
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: User ID.
                password:
                  type: string
                  description: User password.
      responses:
        '200':
          description: Login successful. Returns user token, username, and creation date and shows the home page of the webapp.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: User token.
                  username:
                    type: string
                    description: Username.
                  createdAt:
                    type: string
                    description: Creation date.
        '401':
          description: Invalid credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Invalid Credentials.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error information.
  /getQuestion:
    post:
      summary: Gets a question for the game.
      operationId: getQuestion
      responses:
        '200':
          description: Gets a question for the game successfully. Returns que title of the question, the correct answer and an array with the correct and incorrect answer randomly ordered.
          content:
            application/json:
              schema:
                type: object
                properties:
                  question:
                    type: string
                    description: Title of the question.
                  correctAnswerLabel:
                    type: string
                    description: The correct answer.
                  answerLabelSet:
                    type: array
                    items:
                      type: string
                    description: An array with all the answer, 1 correct and 3 incorrect.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error information.
  /saveHistorial:
    post:
      summary: Saves the data of a question the user answered in the database.
      operationId: saveHistorial
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  description: question title 
                answersArray:
                  type: array
                  items:
                    type: string
                  description: array with all the answers
                correctAnswer:
                  type: string
                  description: correct answer
                selectedAnswer:
                  type: string
                  description: selected answer
                correct:
                  type: boolean
                  description: true if the answer is correct, false if it is incorrect
                username:
                  type: string
                  description: username of the user logged in
      responses:
        '200':
          description: Saves the data into the database. Returns a message to confirm it was a success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: message of success.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error information.
  /getHistorial:
    post:
      summary: gets the data of all games and questions of the user logged in.
      operationId: getHistorial
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: username of the user logged in
      responses:
        '200':
          description: gets the data from the database for the user logged in. Returns an array with all the games and questions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  games:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                          description: question title 
                        answers:
                          type: array
                          items:
                            type: string
                          description: array with all the answers
                        correctAnswer:
                          type: string
                          description: correct answer
                        selectedAnswer:
                          type: string
                          description: selected answer
                        answeredRight:
                          type: boolean
                          description: true if the answer is correct, false if it is incorrect
                    description: message of success.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error information.